# Default state for all rules
default: true

# Multiple consecutive blank lines
MD012:
  maximum: 3

# Line length
MD013:
  line_length: 256
  code_block: false
  tables: false

# Multiple headings with the same content
MD024: false

# Code block style
MD046: false

# Accept both atx and setext header style
MD003: false

# Table column style
MD060:
  aligned_delimiter: false
  style: any
