# Default state for all rules
default: true

# Multiple consecutive blank lines
MD012:
  maximum: 3

# Line length
MD013:
  line_length: 256
  code_block: false
  tables: false

# Code block style
MD046: false

# Accept both atx and setext header style
MD003: false
